#!/bin/bash

# راهنمای کامل آپلود به GitHub

echo "📤 آپلود پروژه به GitHub"
echo "=========================="
echo ""
echo "گزینه ۱: استفاده از Personal Access Token"
echo "-------------------------------------------"
echo ""
echo "۱. برو به: https://github.com/settings/tokens"
echo "۲. Generate new token (classic)"
echo "۳. Note: Hermes Calculator"
echo "۴. Scope: فقط 'repo' رو تیک بزن"
echo "۵. Generate token"
echo "۶. Token رو کپی کن"
echo ""
echo "۷. این دستور رو اجرا کن:"
echo "   git push -u origin main"
echo ""
echo "   Username: rezaacheravi027-rgb"
echo "   Password: [TOKEN رو بچسبون]"
echo ""
echo "=========================="
echo ""
echo "گزینه ۲: استفاده از GitHub Desktop (ساده‌تر)"
echo "----------------------------------------------"
echo ""
echo "۱. دانلود GitHub Desktop: https://desktop.github.com"
echo "۲. نصب و لاگین کن"
echo "۳. File → Add Local Repository"
echo "۴. پوشه: /Users/rezach/calculator-app"
echo "۵. دکمه 'Publish repository' رو بزن"
echo ""
echo "=========================="
